# Source Zgen and create init file if necessary
# Add custom Zsh plugins to .zgen-setup.zsh
source ~/.zgen-setup.zsh

# Add customizations below
export ENABLE_DOCKER_PROMPT=true
export LAZY_NODE_PROMPT=true

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$HOME/.rvm/bin:$GOPATH/bin:$PATH"

alias e.rc="atom ~/dotfiles"
alias cd.rc="cd ~/dotfiles"
alias git=hub

export GOPATH=/Users/frybr02/golang
export PATH="/usr/local/opt/e2fsprogs/bin:$PATH"
export PATH="/usr/local/opt/e2fsprogs/sbin:$PATH"

VISUAL=atom
alias e.="${VISUAL:-vi} ."

[ -f /usr/local/opt/dvm/dvm.sh ] && . /usr/local/opt/dvm/dvm.sh
[[ -r $DVM_DIR/bash_completion ]] && . $DVM_DIR/bash_completion

alias dog='pygmentize -g'

echo "SOURCING ZSH RC!!!"
